# Input the path information for Conda and the workflow directories
workflow_dir: "/path/to/nanopore-workflow"
conda_dir: "/path/to/conda/envs/nanopore-workflow/bin"

# Input sample names to be analyzed.  The folder for each sample should be in the same directory as this file.
samples: ['Sample_1', 'Sample_2']

# Input which samples from above are normals or tumors. All tumors will be compared against all normals for coverage plots.
normals: ['Sample_1']
tumors: ['Sample_2']

# Input the sample information.  
Sample_1: path/to/Sample_1.fastq
Sample_2: path/to/Sample_2.fastq
